# Generated by Django 3.1 on 2020-08-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('about_you', models.CharField(default='Not more than 250 characters', max_length=250)),
                ('photo', models.ImageField(max_length=255, upload_to='')),
            ],
        ),
    ]
