# Generated by Django 3.1 on 2020-08-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200828_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('comment', models.TextField(default='Enter your text here')),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
